### ISSUE TITLE
Ctrl click on blueprint opens it on a new tab, but we can't close the modal

### ISSUE THREAD

**Issue by paullouppe** [rickyzhangca/fprints-xyz#1]
Redo the bug : 
- Ctrl click on one of the blueprints, like on the home page
- it opens the popup in the new tab
- we can't close the popup

Maybe a nav queuing issue ?

**Comment by rickyzhangca** [comment]
thanks! yes the back navigation should be smarter, previously it goes to the previous page and in this case it has no previous  page to go to, it should be smarter now! lemme know if still issues
