### ISSUE TITLE
Collecting only works on the first item

### ISSUE THREAD

**Issue by Na3blis** [rickyzhangca/fprints-xyz#12]
I hit the collect button on a blueprint, then tried to 'collect' another item, and I get a 409.
```
POST https://tutpmokznoxsgodpklag.supabase.co/rest/v1/collection_blueprints 409 (Conflict)
```

**Comment by rickyzhangca** [comment]
Thank you for letting me know, taking a look!

**Comment by rickyzhangca** [comment]
should work now, lemme know if still problemetic
