### ISSUE TITLE
After authorization through Github, you will be redirected to an unknown domain

### ISSUE THREAD

**Issue by click0** [rickyzhangca/fprints-xyz#2]
After authorization through Github, you will be redirected to an unknown domain.

![изображение](https://github.com/user-attachments/assets/83568d53-1e43-4f66-bd73-4b51c8004686)

**Comment by rickyzhangca** [comment]
the auth is provided by https://supabase.com/, the free tier which the site is currently running on (may bump up depending on the load) does not support custom domain so it show supabase and the project id, looks a bit sketchy but don't worry!
