### ISSUE TITLE
Blueprint creation: UI provides no feedback when uploading blueprint. Clicking Create multiple times creates duplicates

### ISSUE THREAD

**Issue by Jetsparrow** [rickyzhangca/fprints-xyz#3]
When creating a blueprint with all the required fields filled, clicking the **Create** button provides no feedback. The user is unsure if anything is happening.  
It feels like a validation error happended that is not properly communicated, so the user may try to edit the submission and click **Create** again.  
This starts another upload, and creates multiple blueprints that are either identical, or differ only slightly.
After the upload is finished, the user is redirected to the last blueprint uploaded, and may remain unaware that they have uploaded duplicates.

Expected behaviour:   
When **Create** is clicked the editor locks, the **Create** button disables, and an activity indicator is shown so that the user knows something is happening. 
Only one blueprint is created.

**Comment by rickyzhangca** [comment]
thanks, noted, I was testing with smaller images while devloping, in real world many images probably is bigger and takes longer, let me add a loading state or something!

**Comment by rickyzhangca** [comment]
ok changes are live, now the create button will be diabled and show "creating..." during image uploading and other steps before blueprint is fully created, lemme know if still issues!

**Comment by Jetsparrow** [comment]
Confirming fix 👍 

You might want to delete some of the duplicates that were upload prior to the fix by hand, there are 4 sets on the main page right now.
