### ISSUE TITLE
Cant create new blueprints due to constantly resetting input fields

### ISSUE THREAD

**Issue by SemiCicada** [rickyzhangca/fprints-xyz#4]
On Firefox, after the first blueprint I created it seems like I can't create any more.

When clicking the create blueprint button, I see the menu like usual.  
But if I try to enter anything in the text fields (Blueprint string, title, description), then my input gets erased. I see my text for one frame before my inputs are getting altered back to nothing. However, if I copy and paste a full blueprint string, then it takes in the entire string in the single frame the text exists, and then my blueprint shows up. If I enter text in the title, I do get text suggestions, but clicking them does nothing.

Clicking the image upload opens up the file explorer like usual, but selecting an image does nothing.

The tags and "Keep private" buttons don't work for me either. The tag button in particular triggers a 1-frame change in the menu and then it quickly goes back to being empty.

**Comment by rickyzhangca** [comment]
fixed, live in prod now, for some reason the bug doesn't happen in local development so i overlooked, big thanks!!! @SemiCicada
