### ISSUE TITLE
Collection Numbers when 0 are not spaced from Label

### ISSUE THREAD

**Issue by msarchet** [rickyzhangca/fprints-xyz#5]
Created a new account to upload blue prints. I see that the numbers when they are 0 next to `Liked`, `My collection` and `My prints` are shown as` Liked0`, `My collection0`, and `My prints0`. No space between 0 and the label. When I added a print it moved it to be` My prints 1` with the space as expected.

![image](https://github.com/user-attachments/assets/e145d70f-3618-4741-bbf6-fcf150d7da22)

**Comment by rickyzhangca** [comment]
thank you, a fix is in prod, now hiding the 0, appreciated

<img width="610" alt="image" src="https://github.com/user-attachments/assets/4e14a07e-96ef-424c-819c-a07e7707bbc1">
