### ISSUE TITLE
Changing pages doesn't scroll back to top

### ISSUE THREAD

**Issue by Na3blis** [rickyzhangca/fprints-xyz#7]
When you select page 2, it doesn't bring you back to the top of the page. I wasn't really paying attention and after a few pages realized I was only looking at the bottom two rows and missed most the blueprints since it just stayed at the bottom of the page

**Comment by rickyzhangca** [comment]
Thank you! Fixing soon.

**Comment by rickyzhangca** [comment]
Fix is live in prod, thanks again
