### ISSUE TITLE
Cannot edit blueprint because "Remixed from" field is empty.

### ISSUE THREAD

**Issue by Mammad900** [rickyzhangca/fprints-xyz#9]
The blueprint in question: https://fprints.xyz/blueprint/86ec1b13-9e2a-4c79-81c8-5f816fe5ee32

The "remixed from" field is optional when first creating the blueprint, but is required when editing it.
![image](https://github.com/user-attachments/assets/8269561b-c07d-45e2-89d5-00fcf80826a6)

This blueprint book is not copied from any other website (I made it myself and uploaded it here first) so there's nothing to put there. For the time being I used the URL of the blueprint itself (on fprints) as a workaround.

**Comment by rickyzhangca** [comment]
hi! was due to a bug where the validator tries to validate empty string to url, fixed it, should work now! i tried with a hello world post, let me know if still issues! @Mammad900

**Comment by Mammad900** [comment]
Can confirm it's fixed.
